modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/quiqueck/WorldWeaver/issues"

[[mods]]
modId="wover"
version="${version}"
displayName="WorldWeaver"
description="Unleash your world-building potential with WorldWeaver, a Minecraft utility mod for NeoForge, simplifying tasks and enhancing the possibilities of data-driven world generation."
authors="Quiqueck"
displayURL="https://github.com/quiqueck/WorldWeaver"
logoFile="assets/wover/icon.png"

[[dependencies.wover]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.wover]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.wover]]
modId="wunderlib"
mandatory=true
versionRange="[21.0.8,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="wover.core.mixins.common.json"

[[mixins]]
config="wover.datagen.mixins.common.json"

[[mixins]]
config="wover.event.mixins.common.json"

[[mixins]]
config="wover.event.mixins.client.json"

[[mixins]]
config="wover.ui.mixins.common.json"

[[mixins]]
config="wover.ui.mixins.client.json"

[[mixins]]
config="wover.tag.mixins.common.json"

[[mixins]]
config="wover.item.mixins.common.json"

[[mixins]]
config="wover.item.mixins.client.json"

[[mixins]]
config="wover.block.mixins.common.json"

[[mixins]]
config="wover.poi.mixins.common.json"

[[mixins]]
config="wover.recipe.mixins.common.json"

[[mixins]]
config="wover.recipe.mixins.client.json"

[[mixins]]
config="wover.potion.mixins.common.json"

[[mixins]]
config="wover.preset.mixins.common.json"

[[mixins]]
config="wover.preset.mixins.client.json"

[[mixins]]
config="wover.math.mixins.common.json"

[[mixins]]
config="wover.structure.mixins.common.json"

[[mixins]]
config="wover.surface.mixins.common.json"

[[mixins]]
config="wover.feature.mixins.common.json"

[[mixins]]
config="wover.biome.mixins.common.json"

[[mixins]]
config="wover.generator.mixins.common.json"

[[mixins]]
config="wover.generator.mixins.client.json"

[modproperties.wover]
updater_icon="icon_updater.png"

[modproperties.wover.downloads]
modrinth="https://modrinth.com/mod/worldweaver"
curseforge="https://legacy.curseforge.com/minecraft/mc-mods/worldweaver"
