modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/quiqueck/WorldWeaver/issues"

[[mods]]
modId="wover-core"
version="${version}"
displayName="WorldWeaver - Core API"
description="Provides Common functionality for our WorldWeaver Mods."
authors="Quiqueck"
displayURL="https://github.com/quiqueck/WorldWeaver"
logoFile="assets/wover-core/icon.png"

[[dependencies.wover-core]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.wover-core]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="wover.core.mixins.common.json"
