modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/quiqueck/WorldWeaver/issues"

[[mods]]
modId="wover-surface"
version="${version}"
displayName="WorldWeaver - Surface API"
description="Provides A Registry for SurfaceRules."
authors="Quiqueck"
displayURL="https://github.com/quiqueck/WorldWeaver"
logoFile="assets/wover-surface/icon.png"

[[dependencies.wover-surface]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.wover-surface]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="wover.surface.mixins.common.json"
