modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/quiqueck/WorldWeaver/issues"

[[mods]]
modId="wover-structure"
version="${version}"
displayName="WorldWeaver - Structure API"
description=""
authors="Quiqueck"
displayURL="https://github.com/quiqueck/WorldWeaver"
logoFile="assets/wover-structure/icon.png"

[[dependencies.wover-structure]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.wover-structure]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="wover.structure.mixins.common.json"
