modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/quiqueck/WorldWeaver/issues"

[[mods]]
modId="wover-recipe"
version="${version}"
displayName="WorldWeaver - Recipe API"
description=""
authors="Quiqueck"
displayURL="https://github.com/quiqueck/WorldWeaver"
logoFile="assets/wover-recipe/icon.png"

[[dependencies.wover-recipe]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.wover-recipe]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="wover.recipe.mixins.common.json"

[[mixins]]
config="wover.recipe.mixins.client.json"

[[mixins]]
config="wover.potion.mixins.common.json"
