modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/quiqueck/WorldWeaver/issues"

[[mods]]
modId="wover-common"
version="${version}"
displayName="WorldWeaver - Common API"
description="Common interfaces used by other WorldWeaver mods."
authors="Quiqueck"
displayURL="https://github.com/quiqueck/WorldWeaver"
logoFile="assets/wover-common/icon.png"

[[dependencies.wover-common]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.wover-common]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
