modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/quiqueck/WorldWeaver/issues"

[[mods]]
modId="wover-events"
version="${version}"
displayName="WorldWeaver - Events API"
description="Provides an API for registering events in the Lifecycle of a Minecraft World."
authors="Quiqueck"
displayURL="https://github.com/quiqueck/WorldWeaver"
logoFile="assets/wover-events/icon.png"

[[dependencies.wover-events]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.wover-events]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="wover.event.mixins.common.json"

[[mixins]]
config="wover.event.mixins.client.json"
